name = "sonbarsa-digital-growth-1"
compatibility_date = "2024-11-01"
main = "worker.js"

routes = [
  { pattern = "sonbarsa.com", custom_domain = true },
  { pattern = "www.sonbarsa.com", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "sonbarsa-db"
database_id = "8be93a83-9122-494e-939e-0bc246d9e4f9"
migrations_dir = "migrations"

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = true
html_handling = "drop-trailing-slash"
not_found_handling = "404-page"
